1. added column isActive on listing.js,2. created a SQL dir with List…
a-ashbeck/project-2 pull request #17
Opened 2017-02-08 03:15 UTC by Pnickolas1

1. added column isActive, boolean value, defaulted to true on Listing.js
2. created a SQL_DummyData folder with Listings_Dummy and corresponding dummy data

2017-02-08 03:17 UTC, a-ashbeck reviewed
@Pnickolas1 You mentioned you made a change to the `listing.js` file? I am not seeing that here, just the dummy data addition.

2017-02-08 03:21 UTC, Pnickolas1 commented
@a-ashbeck sorry, I had to git add -A , you will see changes on Listings.js now

2017-02-08 03:25 UTC, a-ashbeck commented on config/config.json
> +        "port": 8889,
@Pnickolas1 Looks like you forgot your login info in the `config.js`

2017-02-08 03:25 UTC, a-ashbeck commented on models/listing.js
> +        },
Cool, this should work perfectly.

2017-02-08 03:33 UTC, a-ashbeck requested changes
This ought to be good to go once the login info is taken out. Otherwise, it looks good! Thanks!

2017-02-08 13:27 UTC, kshiro622 commented
We've merged pull requests since this once so I think you'll need to do a git fetch/rebase master.

2017-02-09 00:13 UTC, a-ashbeck approved these changes

2017-02-09 00:14 UTC, merged